### ISSUE TITLE
echo "> >> < * ? [ ] | ; [ ] || && ( ) & # $ \ <<" 

### ISSUE THREAD

**Issue by Chr-ss** [britesramos/Minishell#3]
15 | echo "> >> < * ? [ ] | ; [ ] || && ( ) & # $ \ <<" 
mini output = (minishell: syntax error near unexpected token `||')
bash output = (> >> < cases e2e.sh files files_temp interactive.sh logs norminette_tester README.md util xdotool ? [ ] | ; [ ] || && ( ) & # $ \ <<)
16 | echo '> >> < * ? [ ] | ; [ ] || && ( ) & # $ \ <<' 
mini output = (minishell: syntax error near unexpected token `||')
bash output = (> >> < cases e2e.sh files files_temp interactive.sh logs norminette_tester README.md util xdotool ? [ ] | ; [ ] || && ( ) & # $ \ <<)
19 | echo "$" 
mini output = ()
bash output = ($)

**Comment by britesramos** [comment]
Fixed!
